# PathLike | str combination is used due to problems with Pylance

import json
import os
import shutil
import time
from contextvars import ContextVar
from os import PathLike
from pathlib import Path

from installer.core import Model
from installer.project import Project
from installer.sdk._host import Host

__all__ = [
    "Host",
    "Model",
    "Project",
    "generate_build_info",
    "include",
    "include_python",
    "init_build",
    "project",
]

_projectfile_context = ContextVar("project_function_context")


def _set_project(c: Project):
    _projectfile_context.set(c)


def project() -> Project:
    return _projectfile_context.get()


def init_build():
    p = project()
    shutil.rmtree(p.build_dir, ignore_errors=True)
    p.build_dir.mkdir(parents=True, exist_ok=True)


def generate_build_info(target: PathLike | str):
    p = project()
    build_time = time.time()

    print(f"Generate build info to '{target}'.")
    target = Path(p.source_dir, target)
    extension = target.suffix.removeprefix(".")
    auto_message = "Auto-Generated by the Dome Build System. Edit responsibly."
    content = ""
    display_name = "" if p.name is None else p.name
    if extension == "py":
        content = (
            f"# {auto_message}\n"
            f"id = {json.dumps(p.id)}\n"
            f"name = {json.dumps(display_name)}\n"
            f"version = {json.dumps(p.version)}\n"
            f"time = {build_time}\n"
            f"debug = {'True' if p.debug else 'False'}"
        )
    elif extension in ["js", "ts"]:
        bracket_left = "{"
        bracket_right = "}"
        content = (
            f"// {auto_message}\n"
            f"const id = {json.dumps(p.id)};\n"
            f"const name = {json.dumps(display_name)};\n"
            f"const version = {json.dumps(p.version)};\n"
            f"const time = {build_time};\n"
            f"const debug = {'true' if p.debug else 'false'};\n"
            f"export {bracket_left} id, name, version, time, debug {bracket_right};\n"
        )
    else:
        raise Exception(f"Unsupported build info extension '{extension}' at location '{target}'.")
    with target.open("w+") as f:
        f.write(content)


def _looks_like_glob(pattern: str) -> bool:
    """True if *path segment* uses glob metacharacters (pathlib.Path.glob)."""
    return any(ch in pattern for ch in "*?[")


def include(target: Path | str, dest: Path | str | None = None):
    """
    Includes target into a build directory.

    If ``target`` contains glob metacharacters (``*``, ``?``, ``[``), it is resolved
    with :meth:`pathlib.Path.glob` under the project source directory; every match is
    copied into the build tree preserving its path relative to the source root. In that
    case ``dest`` must be omitted (it is not supported for globs).
    """
    ctx = project()
    target = Path(target)
    pattern_str = target.as_posix()

    if _looks_like_glob(pattern_str):
        if dest:
            raise Exception(
                "include() with a glob pattern does not allow `dest`; each match is copied "
                "into the build directory preserving its path relative to the project root."
            )
        matches = sorted(ctx.source_dir.glob(pattern_str))
        if not matches:
            raise Exception(
                f"Cannot find include paths matching glob '{pattern_str}' under '{ctx.source_dir}'."
            )
        print(f"Include glob '{pattern_str}' ({len(matches)} path(s)).")
        for real_item in matches:
            rel = real_item.relative_to(ctx.source_dir)
            out = Path(ctx.build_dir, rel)
            if real_item.is_dir():
                shutil.copytree(real_item, out, dirs_exist_ok=True)
            elif real_item.is_file():
                out.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(real_item, out, follow_symlinks=True)
            else:
                raise Exception(
                    f"Unsupported include glob match '{real_item}' (not a file or directory)."
                )
        return

    real_target = Path(ctx.source_dir, target)

    message = f"Include target '{target}'."
    if dest:
        message += f" Destination is altered to '{dest}'."
    print(message)

    if not real_target.exists():
        raise Exception(f"Cannot find include path '{real_target}'.")
    elif real_target.is_dir():
        if dest == ".":
            for item in os.listdir(real_target):
                item_path = Path(real_target, item)
                dest_path = Path(ctx.build_dir, item)
                if item_path.is_dir():
                    shutil.copytree(item_path, dest_path)
                else:
                    shutil.copy2(item_path, dest_path)
        else:
            shutil.copytree(real_target, Path(ctx.build_dir, dest if dest else target))
    else:
        if dest == ".":
            raise Exception("Include destination of '.' is not allowed for files.")
        shutil.copy2(real_target, Path(ctx.build_dir, dest if dest else target))


def include_python():
    """
    Includes Python files and requirements.txt into the build directory.
    """
    p = project()
    for root, dirs, files in os.walk(p.source_dir):
        if Path(root) == p.source_dir:
            for filename in files:
                if filename in "requirements.txt" or filename.endswith(".py"):
                    include(filename)
        elif Path(root).parent == p.source_dir:
            for filename in files:
                if filename == "__init__.py":
                    include(Path(root).name)
